version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn geoProj.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: geo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
  staticfiles: