# Generated by Django 5.1.2 on 2024-10-25 15:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polygone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('polygone', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('crosses_antimeridian', models.BooleanField(default=False)),
            ],
        ),
    ]
