# Generated by Django 5.1.2 on 2024-10-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polygone',
            old_name='polygone',
            new_name='polygon',
        ),
    ]
